Support to boolector as the SMT solver
trailofbits/manticore pull request #2410
Opened 2021-03-24 19:17 UTC by ggrieco-tob

This branch includes initial support for [boolector](https://github.com/Boolector/boolector). Only recent versions (e.g 3.2.x) are supported. Ancient versions like the one in Ubuntu 18.04 (1.5.x) are not.

2021-03-25 13:30 UTC, ekilmer reviewed
This is exciting! And the process for adding a new solver looks to be very easy :) 

It would be nice to test basic functionality of `boolector` solver in CI as well.

We would need to figure out how to install it into the Ubuntu 18.04 environment and also add some tests that use `boolector`, which I think is as simple as following what's done here https://github.com/trailofbits/manticore/blob/fd69381a2c1cc7f83a1552f7d6fef762bfee1e14/tests/other/test_smtlibv2.py#L1283-L1290

Something like the following:
```python
class ExpressionTestBoolector(ExpressionTest):
    def setUp(self):
        self.solver = BoolectorSolver.instance()
```

2021-03-25 13:30 UTC, ekilmer commented on manticore/core/smtlib/solver.py
> +class Boolector(SMTLIBSolver):
Nit: Would you mind changing this to follow the pattern of the solvers? `BoolectorSolver`

2021-03-25 20:04 UTC, ekilmer requested changes

2021-03-25 20:04 UTC, ekilmer commented on .github/workflows/ci.yml
> +        sudo make DESTDIR=/usr install
Ideally, we wouldn't have to rebuild boolector each time, but that might require messing with GH Actions caching, which can be annoying.

`master` branch has this `Install dependencies` step taking around 1:30 minutes, and now it's around 2:45 or 3 minutes.

@ehennenfent any strong feelings on this? I think maybe opening an issue to figure out caching would be fine?

2021-03-25 20:06 UTC, ekilmer commented on .github/workflows/ci.yml
> +        git checkout "f61c0dcf4a76e2f7766a6358bfb9c16ca8217224"
```suggestion
        # Version 3.2.1
        git checkout "f61c0dcf4a76e2f7766a6358bfb9c16ca8217224"
```

2021-03-26 16:06 UTC, ggrieco-tob commented on manticore/core/smtlib/solver.py
> -        )
boolector seems to need a slightly more general parsing code, which also works for other solvers

2021-03-26 16:12 UTC, ggrieco-tob commented on manticore/ethereum/parsetab.py
> +_lr_signature = "ADDRESS BOOL BYTES BYTESM COMMA FIXED FIXEDMN FUNCTION INT INTN LBRAKET LPAREN NUMBER RBRAKET RPAREN STRING UFIXED UFIXEDMN UINT UINTN\n    T : UINTN\n    T : UINT\n    T : INTN\n
yeap, sorry about that :disappointed:

2021-03-26 16:12 UTC, ggrieco-tob commented on manticore/core/smtlib/solver.py
> +            assert False
Fixed.

2021-03-26 17:04 UTC, ekilmer requested changes
Looking good!! Just a few minor things, and then I think we'll be ready for merge 🎉

2021-03-26 17:04 UTC, ekilmer commented on manticore/core/smtlib/solver.py
> +            base = 16
Minor nit, we could change to the following:
```suggestion
        base = 2
        m = RE_GET_EXPR_VALUE_FMT_BIN.match(t)
        if m is None:
            m = RE_GET_EXPR_VALUE_FMT_DEC.match(t)
            base = 10
        if m is None:
            m = RE_GET_EXPR_VALUE_FMT_HEX.match(t)
            base = 16
```

2021-03-26 17:37 UTC, ekilmer approved these changes
LGTM. Thank you!!

2021-03-26 18:12 UTC, ggrieco-tob commented
@ekilmer can you merge this? Github says:

> You’re not authorized to merge this pull request.

for some reason.. :thinking:

2021-03-26 18:35 UTC, merged