Add link to mate docs in README
trailofbits/manticore pull request #2584
Opened 2022-08-30 15:07 UTC by sschriner

2022-08-30 15:55 UTC, ekilmer requested changes

2022-08-30 15:55 UTC, ekilmer commented on README.md
> +- [MATE: Merged Analysis To prevent Exploits](https://github.com/GaloisInc/MATE)
MATE is a large system, we should call out which subdirectories specifically use Manticore. Let's also link to the docs page(s) here https://galoisinc.github.io/MATE/dwarfcore.html and https://galoisinc.github.io/MATE/mantiserve.html

2022-08-30 16:38 UTC, ekilmer approved these changes
LGTM! Thanks!

2022-08-30 16:38 UTC, ekilmer commented on README.md
> +  *
```suggestion
```

2022-09-07 13:15 UTC, Boyan-MILANOV requested changes
Added a suggestion for under-constrained manticore docs. Other than that LGTM!

2022-09-07 13:15 UTC, Boyan-MILANOV commented on README.md
> +  * [Dwarfcore:](https://galoisinc.github.io/MATE/dwarfcore.html) Plugins and detectors for use within Mantiserve engine during exploration
```suggestion
  * [Dwarfcore:](https://galoisinc.github.io/MATE/dwarfcore.html) Plugins and detectors for use within Mantiserve engine during exploration 
  * [Under-constrained symbolic execution](https://github.com/GaloisInc/MATE/blob/main/doc/under-constrained-manticore.rst) Interface for symbolically exploring single functions with Manticore
```

2022-09-13 16:09 UTC, Boyan-MILANOV approved these changes

2022-09-13 16:09 UTC, merged